import { mkdir, writeFile, rename } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cloudflaredVersion = '2026.10.0';
const response = await fetch(`https://api.github.com/repos/cloudflare/cloudflared/releases/tags/${cloudflaredVersion}`, { headers: { 'User-Agent': 'Concord-build' } });
if (!response.ok) throw new Error(`Não consegui consultar o Cloudflared: HTTP ${response.status}`);
const release = await response.json();
const asset = release.assets.find(item => item.name === 'cloudflared-windows-amd64.exe');
if (!asset?.digest?.startsWith('sha256:')) throw new Error('O release não tem um checksum SHA-256 para conferir o executável.');
console.log(`Preparando Cloudflared ${release.tag_name}…`);
const download = await fetch(asset.browser_download_url);
if (!download.ok) throw new Error(`Falha no download: HTTP ${download.status}`);
const bytes = Buffer.from(await download.arrayBuffer());
const sha = createHash('sha256').update(bytes).digest('hex');
if (asset.digest !== `sha256:${sha}`) throw new Error('Checksum do Cloudflared não confere.');
await mkdir(path.join(root, '.runtime'), { recursive: true });
await writeFile(path.join(root, '.runtime', 'cloudflared.exe.part'), bytes);
await rename(path.join(root, '.runtime', 'cloudflared.exe.part'), path.join(root, '.runtime', 'cloudflared.exe'));
await writeFile(path.join(root, '.runtime', 'cloudflared-version.json'), JSON.stringify({ version: release.tag_name, sha256: sha, source: asset.browser_download_url }, null, 2));
const license = await fetch(`https://raw.githubusercontent.com/cloudflare/cloudflared/${cloudflaredVersion}/LICENSE`);
if (!license.ok) throw new Error('Não consegui obter a licença do componente de conexão.');
await writeFile(path.join(root, '.runtime', 'cloudflared-LICENSE.txt'), await license.text(), 'utf8');
console.log('Cloudflared baixado e checksum conferido.');
